---
title: "Bireylerin Gelirleri ve Tüketimleri"
author: 
  - İrem SEFER[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 20080296, [Github Repo](https://github.com/iremsefer38/arasinav.git)


# Giriş
  Bireylerin tüketimleri ve gelirleri arasında nasıl bir ilişki olduğunu, görece düşük gelirli ve görece yüksek gelirleri bireylerin tüketim harcamaları arasındaki farkları araştıracağım. Veri setimi bir kaynaktan bulmadım kendim anket yolu ile oluşturdum. Sorularımı araştırmak ve karşılaştırmak istediğim konular üzerinden seçtim. Bireylerin gelirleri ve tüketimlerini araştıracağım için veri setimi hazırlarken bir evin içinde birden fazla kişinin yaşadığı bireylerle anket yapmadım. Evin içinde birlikte yaşayan kişilerin ortak giderlerdeki kullanım payları eşit olmayabileceği gibi aynı zamanda ailesi ile yaşayan gençler ortak harcamaları ebeveynleriyle aynı oranda paylaşmayabilirler örneğin daha çok kazanan aile ekonomisine daha çok destekte bulunabilir bu gibi etkenlerden dolayı şeffaf olması amacıyla veri setimi tek başına yaşayan kişilerle sınırlandırdım. Yaşadığım site sadece 1+1 dairelerden oluştuğu ve çoğunlukla bireyler tek başına yaşadıkları için başlangıçta sitemdeki komşularıma anketimi yaptım. Komşularımdan elde ettiğim verilere, aralık değerleri belirledim. Bu aralık değerlerini ve sorularımı hazırladıktan sonra Ankara’da anketimin geri kalan kısmını tamamladım.  
Okuduğum makalede Kocaeli Üniversitesinde yapılan bir araştırmada harcama kategorileri üzerinden anket yapılmış ancak ben sorularımı hazırlarken ülkenin içinde bulunduğu mevcut enflasyon seviyesinde bireylerin ne kadar kişisel harcama yapabildiklerini görmek istedim. Bu yüzden veri setimi hazırlarken öncelikle bireylerin mutfak harcamaları ve kiraları gibi aylık otonom harcamalarıyla ilgili bilgi edinmeye çalıştım. Sonrasında son bir yıl içerisinde kaç kere kültürel ve sanatsal aktivelere katılabildiniz gibi daha seçici ve farklı sorular sormaya çalıştım. 

## Çalışmanın Amacı
 Çalışmamın amacı, bireylerin gelirlerini otonom harcamaları dışında hangi alanlara harcadıklarını ve ne gibi kişisel harcamalar yapmayı tercih ettiklerini görmek. Örneğin gelişmiş ülkelerde olduğu gibi Türkiye’de de bireyler hobilerine bütçe ayırabiliyorlar mı veya yaş ile aylık gelir arasında bir ilişki var mı yaş arttıkça gelir de artar mı gibi birden fazla değişkenin birbirleriyle etkileşimlerini araştırmak. Aynı zamanda tüm değişkenlerin birbirleriyle etkileşimlerini test etmek. 
Görece düşük gelirli bireylerin, kendilerine kişisel bütçe oluşturma imkanlarının olup olmadığının yanı sıra projemde görmek istediğim bir diğer konu görece yüksek bireyli kişiler, gelirlerini kendilerini geliştirmek için mi harcıyorlar yoksa daha çok birikim yapmaya mı odaklılar? 
Keynes’e göre bireyler, gelirleri arttıktan sonra, çok hızlı bir şekilde tüketimlerini arttırmıyorlar. Bireylerin gelir artışından sonra tüketimlerini arttırmaları arasında belli bir zaman var. Öncelikle tasarruflarını sonrasında tüketimlerini arttırıyorlar. Benim veri setimde birçok asgari ücretle çalışan birey var, bu bireyler gelir artışını 3 ay önce yaşadılar. Aynı zamanda analizimde bu bireylerin 3 aylık bir sürede, tüketimlerini yeni asgari ücret seviyesine adapte edip etmediklerini inceleyerek, Keynes’in tezinin sorgulamasını yapmaya çalışacağım.


## Literatür 
  Bireylerin gelirleri ve tüketimleri ekonomide birçok şeyin göstergesidir. Tasarruf eğilimlerini ele alırsak, bize birçok şeyi gösterir. Bireylerin tasarruf eğilimleri yüksekse bankacılık sektörü iyi çalıştığını varsaydığımız bir ülkede yatırımlarda fazla olacaktır. Yatırımların fazla olduğu ülkede üretim düzeyi de yüksektir. Bireylerin tasarruf eğilimi, bir kartopu etkisi gibi ülkenin ekonomik düzeyi için çok büyük bir önem arz eder. 
Bireyler tasarruf yerine, kendilerini geliştirmeye yönelik tüketimlerde bulunuyorsalar bu da tasarruf eğilimi gibi bir kartopu etkisi yaratarak verimliliğin artmasından kaynaklı olarak üretimi, arttırmış olacaktır. Kendilerini geliştirmek ve dolayısıyla verimliliklerini arttırmak için harcamalarda bulunmak örneğin bir yabancı dil kursuna gitmek sosyalleşmeyi ve hayat kalitesini de artıracağından dolayı olumlu bir psikolojik etki yaratırken, verimliliklerini arttırmak yerine müze gezmek gibi kültürel ve sanatsal aktivitelere harcama yapmanın da psikolojik olarak olumlu bir etki yaratacağını araştırmalar bize gösteriyor. Dolayısıyla hobilerine zaman ayırabilen, kendini geliştirmek için bütçeye sahip olan bireyler bu olanaklara sahip olmayan bireylere göre çok daha yüksek seviyede bir verimlilik sergileyeceklerdir.  İş çıkışı bir müze gezmeye gidecek bireyin verimliliği, iş çıkışı evinde görece sağlıksız ve ucuz gıdalar tüketerek ekonomisini düzenlemeye çalışacak bireyden daha yüksek bir verimlilik göstermesi yüksek olasılıktır. 
Bu varsayımlar sonucunda karşımıza gelişmekte olan ülkeler için 2 farklı seçenek çıkıyor. Gelişmekte olan ülkelerin gelişmesi için ihtiyaçları olanlar konusunda sadece bireylerin harcamalarıyla sınırlandırdığımızda, gelişmekte olan ülkelerin gelişmiş olabilmesi için o ülkedeki bireyler ya tasarrufta bulunmalı ya da kendilerini geliştirmeye, işgücünde verimliliği arttırmaya yönelik harcamalarda bulunmalıdır. Hükümetler de ekonomik büyüme için bu harcamaları destekleyecek politikalar yürütebilir. Bende projemde Türkiye’deki bireyler otonom harcamalarından kalan bütçelerini tasarrufa veya kendilerini geliştirmeye mi harcıyorlar yoksa farklı harcamalara mı yöneliyorlar bunu test edeceğim. Tabi ki otonom harcamalarından geriye bir bütçelerinin kalmayabileceği ihtimalini de gözden kaçırmamak gerekir.
 Tüketim harcamalarını sadece ülkenin ekonomik yararı başlığında değerlendirmeye çalıştım. Bu kısımda ise tüketim harcamalarının bireylere olan etkisini değerlendirmek istiyorum. Bireyler için tüketim harcamalarındaki en önemli otonom kalemlerden biri mutfak harcamaları. Bireylerin mutfak harcamaları onların aynı zamanda sağlıklarını da ifade ediyor. Bir birey güncel olarak aylık ne kadar sağlıklı gıda ne kadar sağlıksız gıda harcaması yapıyor bunun bilgisine sahip değilim. Başlangıçta bu bilgiyi de veri setime eklemek istedim ancak genel olarak bireylerde bu bilginin net farkında olmadıkları için sağlıklı yanıtlar alamadım bu yüzden bu soruyu ve dolayısıyla kavramı yüksek mutfak harcamalarının daha sağlıklı, görece daha düşük yapılan mutfak harcamalarının daha sağlıksız hazır gıdalardan oluştuğunu varsayıyorum. Sürekli akşam yemeğini ucuza mâl etmeye çalışmak, makarna veya hazır gıda ile beslenmek doğal olarak sağlıksız bir bireye sebep olacaktır. Bazı bireyler gelir yetersizliğinden dolayı buna mecbur kalsa da bazı bireyler kişisel olarak bunu tercih edebilir. Daha fazla birikim yapmak veya farklı harcamalara daha fazla bütçe ayırabilmek için yetersiz besleniyor ve hatta bunun ciddiyetinin farkında olmayabilir. Yetersiz beslenme birçok hastalığa davet çıkartma dışında kişiye ruhsal ve psikolojik olarak da zarar veriyor.  Sinirlilik hali, unutkanlık ve kafa karışıklığı, çabuk yorulma ve halsizlik ilk dikkat çeken ruhsal ve psikolojik etkiler.

 Elbette ki kimsenin yetersiz beslenmek zorunda kalmasını istemeyiz ancak yetersiz beslenmek zorunda kalan bireylerin ülkeye etkisine de değinmek istiyorum. Bireyi etkileyen her şey toplumları ve ülkelerin mevcut durumlarını da etkilediğinden dolayı, yetersiz beslenmenin de ülke için bir maliyeti var. Yetersiz beslenmenin yarattığı psikolojik zararın maliyetini görmezden gelirsek. Yetersiz beslenen bir birey sürekli olarak rahatsızlanabilir hatta çok daha büyük ve tedavisi maliyetli hastalıklara yakalanabilir. Türkiye’yi baz alırsak çalışan bir bireyin sürekli olarak rahatsızlanması devlete bir ekonomik sorumluluk doğuruyor. Bunun yanı sıra bireylerin yetersiz beslenmekten kaynaklı, vitamin eksikleri ve bağışıklık sisteminde zayıflamalar olası bir salgın durumunda bireylerinin birçoğunun yetersiz beslendiği bir ülkede bağışıklık sistemlerinin zayıf olması sebebiyle salgının olağandan hızlı yayılmasına ve ülkedeki tüm vatandaşlara tehlike oluşturmasına sebep olabilir. Projemde Türkiye’deki bireylerin gelirlerine oranla ne kadar mutfak harcaması yaptıklarını ve gelirleri arttıkça daha sağlıklı beslenmeye mi yoksa farklı harcamalara mı yöneldiklerini analizime ekleyeceğim.


\newpage
# Kaynakça {#references}
<div id="refs"></div>

